name: Publish to NPM

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run test
    - name: Commit report
      run: |
        git config --global user.name 'CI Bot'
        git config --global user.email '1761608+gregbacchus@users.noreply.github.com'
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
